# small.yaml file

storage:
  data_dir: data/relationship_advice
  savePath: models/relationship_advice
model:
  hidden_size: 300
  dropout: 0.1
training:
  data_dir: data/relationship_advice
  learning_rate: 0.1
  val_freq: 2000
  summary_freq: 100
  batch_size: 10
  num_epochs: 1
  max_len: 1500
