# small.yaml file

storage:
  data_dir: data/reddit-small
  savePath: models/reddit-small
model:
  hidden_size: 300
  dropout: 0.1
training:
  data_dir: data/reddit-small
  learning_rate: 0.1
  val_freq: 100
  summary_freq: 10
  batch_size: 10
  num_epochs: 1
